---
title: "20181025"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
library(showtext)

showtext_auto(enable=TRUE)
theme_set(theme_classic())
```
```{r}
p1 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() 
p1
```
```{r}
p1+
  theme(panel.grid.major.y=element_line())->p1
p1
```



```{r}
p1 + theme(axis.text = element_text(colour = "blue"), axis.text.x = element_text(hjust=1))
```

```{r}
p2 <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point() 
p2
```

```{r}
p2+
  theme(axis.line.y=element_line())->p2
p2
```



```{r}
p2 + theme(axis.line.y = element_line(size=0))
```
```{r}
 p2 + theme(  axis.line.y = element_blank())+ theme(axis.text = element_text(colour = "blue"), axis.text.x = element_text(hjust=1))
```

```{r}
mtcars2 <- mtcars[1:15, ]
mtcars2$name <- row.names(mtcars2)

ggplot(mtcars2, aes(x = name, y = mpg, fill = name)) + 
  geom_bar(stat = 'identity', position = "identity") +
  guides(fill = FALSE) + 
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1)) 
```
```{r}
p1 + theme(axis.title.y = element_text(size = rel(1.5), angle = 90))
```



